const fs = require('fs');
let code = fs.readFileSync('src/App.tsx', 'utf8');

const strat1 = `{ id: 'oiWallRejection', familyKey: 'OI_WALL_REJECTION', name: '5. OI Wall Rejection (OI_WALL_REJECTION)', desc: 'Priority 5 | Rejection trades when 1.5x dominant OI walls reject price 2+ times & begin unwinding.', rr: '>= 0.8R to 1.2R' },`;
const newStrat1 = `                        { id: 'oiWallRejection', familyKey: 'OI_WALL_REJECTION', name: '5. OI Wall Rejection (OI_WALL_REJECTION)', desc: 'Priority 5 | Rejection trades when 1.5x dominant OI walls reject price 2+ times & begin unwinding.', rr: '>= 0.8R to 1.2R' },
                        { id: 'technicalConfluence', familyKey: 'TECHNICAL_CONFLUENCE', name: '6. Technical Confluence (TECHNICAL_CONFLUENCE)', desc: 'Priority 1 | Trades based on technical indicators (RSI, MACD, EMA, BB, SuperTrend) voting consensus.', rr: '>= 1.0R' },`;

code = code.replace(strat1, newStrat1);

const strat2 = `{ key: 'oiWallRejection', name: '5. OI Wall Rejection (OI_WALL_REJECTION)', desc: 'Priority 5 | Rejection trades when 1.5x dominant OI walls reject spot price at least 2 times.', win: 'Any (Post Wall Rejection)', rr: '>= 0.8R to 1.2R' }`;
const newStrat2 = `                  { key: 'oiWallRejection', name: '5. OI Wall Rejection (OI_WALL_REJECTION)', desc: 'Priority 5 | Rejection trades when 1.5x dominant OI walls reject spot price at least 2 times.', win: 'Any (Post Wall Rejection)', rr: '>= 0.8R to 1.2R' },
                  { key: 'technicalConfluence', name: '6. Technical Confluence (TECHNICAL_CONFLUENCE)', desc: 'Priority 1 | Trading signals generated by technical indicators (RSI, MACD, EMA, Bollinger Bands, SuperTrend) voting consensus.', win: 'Any (Trend Direction)', rr: '>= 1.0R' }`;

code = code.replace(strat2, newStrat2);

fs.writeFileSync('src/App.tsx', code);
console.log('patched UI');
